### ISSUE TITLE
Delete unused files

### ISSUE THREAD

**Issue by BluesBreaker** [iiasa/g4m#1]
Firstly, we need only increment folder.
Secondly, I suggest restructuring this folder, as it is not increment only.
For example, mai is standalone. So we at least need to change the name, e.g. G4Mmodules. Potentially, put mai to MAI suborder, and Age-structure to age-structure...

**Comment by OlgaTurkovska** [comment]
If we keep just  increment folder, let's have folder for each G4M module. For instance, create MAI folder that will contain:
mai.cc
mai.h
TestMai.cc

**Comment by BluesBreaker** [comment]
this issue is solved in pull request #3
