### ISSUE TITLE
Add script for input data generation

### ISSUE THREAD

**Issue by OlgaTurkovska** [iiasa/g4m#2]
- Add seperate folder to repository for input data generation
- Upload the script 
- Add readme.md file

**Comment by GeorgKindermann** [comment]
The input data generation scripts will only make sense for others when also including the data files.
In case we also publish input data, I would prefer to place it here in a folder.
In case we don't publish here input data, I would prefer to place it in another repository.
For usability for other I would prefer to provide also some data.

**Comment by OlgaTurkovska** [comment]
git has git Large Storage Files extension that allows storing big data files up to 2 Gb without making repository too heavy, I will check the extension and we can use it for data script

**Comment by OlgaTurkovska** [comment]
The other question would be, which resolution do we want to use 0.5 x 0.5 degree or 0.0083333 x 0.0083333 degree?
Different resolution does not make a big difference for the data script however it requires other data sets

From the other point of view, a user can always set the resolution of the output file and make it as precise as it is needed.  In this case, no need for us to put lower resolution. Just need to explain how to change output file resolution in the script.

**Comment by OlgaTurkovska** [comment]
Script for generating input file was added in #6 
Readme file will be added at the later stage.

Discussion on including data files is moved to #7.
