### ISSUE TITLE
deleted unused files? g4m -> g4gm?

### ISSUE THREAD

**Issue by GeorgKindermann** [iiasa/g4m#5]
Looks like we are focusing only on the increment part since "unused" files have been deleted.
With these "unused" files the afforestation/deforestation decision are done.
If we give away this part of g4m to e.g. Mykola than we should give the model the right name: g4gm (global 4rest growth model) like I have done it already in the past publications which are only focusing on growth.

**Comment by BluesBreaker** [comment]
Sounds great!

**Comment by BluesBreaker** [comment]
Could you rename g4m -> g4gm on IIASA repository?

**Comment by GeorgKindermann** [comment]
I think someone of the IIASA group has to create a new branch with the new name (and remove g4m there).

**Comment by OlgaTurkovska** [comment]
What if in the future we are going to upload deleted files? It means we will have to change the name again. Maybe we stay with "g4m" for the moment?

**Comment by GeorgKindermann** [comment]
It depends on what should be done here.
If it should maintain the whole g4m model than the unused files need to stay there.
If it will only look on the growth part than I think it need to be renamed to what it really is.
This one time renaming will not influence uploading ore deleting files in the future as long as this will not remove the core part of what is was named the g4m.

**Comment by OlgaTurkovska** [comment]
In this case, we can rename repository, why creating a new branch?

**Comment by GeorgKindermann** [comment]
Never mind.
Either rename or new branch.
But please make it clear what it deals with.

**Comment by OlgaTurkovska** [comment]
Ok, good then.
@BluesBreaker do you agree that we can keep this repository only on forest growth development?

**Comment by BluesBreaker** [comment]
Let's work with the growth model first. We can add afforestation/deforestation decisions afterwards.
For this reason, we can rename g4m to g4gm and specify that this is the growth part of the g4m. Will this work?

**Comment by GeorgKindermann** [comment]
OK. I have renamed it to g4gm.
