### ISSUE TITLE
Including data files

### ISSUE THREAD

**Issue by OlgaTurkovska** [iiasa/g4m#7]
This issue is a follow-up on the question raised in #2  : 
should data files for input generating script (#6) be uploaded on gitHub and how to proceed with it?

At the current stage, there is no agreement on that. However, it is also not the most urgent question to deal with.

I prefer to leave the question open for discussion here, so we can come back to it when we will have better ideas or necessity to solve it.

**Comment by GeorgKindermann** [comment]
Not to overload master I created the branch application.
There I give in /simple an example with data on half deg resolution.
