### ISSUE TITLE
add scripts to application/16PotForestCover

### ISSUE THREAD

**Issue by OlgaTurkovska** [iiasa/g4m#9]
@GeorgKindermann 

For **application/16PotForestCover**, could you please add scripts that generate the following files:

- forestCoverG4mIrri2015 
- forestCoverG4mCalib2015
- maiG4mMax2010.tif
- maiG4mMax2010irri.tif
- primaryForestG4M2015.tif
- cAg_ha.tif 
- cBg_ha.tif 
- soilc_ha.tif

**Comment by GeorgKindermann** [comment]
Tomorrow I'll be at IIASA and load up the old sources as they are.
They need to be updated, as they are using the NPP-Model-V1 and now there is V2 and maybe Andrey and Anatoly are finishing Version 3.

**Comment by OlgaTurkovska** [comment]
Good.
As far as I know, Version 3 is not ready yet.
How much does it take to update it to V2?

**Comment by GeorgKindermann** [comment]
I have added all the sources as they are. Typical they need to be updated to the current state.
Changing from V1 to V2 might be only to change the NPP-Class.
But there are many other things. E.g. the soilc is done by using yasso07, now there is yasso15.
There are new forest cover maps, human activity maps and so on which should be updated in our datasets.
